repos:
- repo: local
  hooks:
  - id: ruff-check
    name: ruff check
    entry: uv run ruff check sushie tests data
    language: system
    pass_filenames: false
  - id: ruff-format
    name: ruff format check
    entry: uv run ruff format --check sushie tests data
    language: system
    pass_filenames: false
  - id: ty
    name: ty
    description: Type-check with ty.
    entry: uv run ty check sushie tests data
    language: system
    pass_filenames: false
